import sqlalchemy_utils
"""empty message

Revision ID: fb8ca7475856
Revises: d92a81cdff1c
Create Date: 2022-01-16 23:25:05.645543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8ca7475856'
down_revision = 'd92a81cdff1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('ip', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True))
    op.add_column('question', sa.Column('ip', sqlalchemy_utils.types.ip_address.IPAddressType(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'ip')
    op.drop_column('answer', 'ip')
    # ### end Alembic commands ###
